In [ ]:
"Bonjour"

'Bonjour'

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

# Nouvelle section

In [ ]:
import pandas as pd
df = pd.read_excel("clients_fictifs_AML.xlsx")
df

,ID_Client,Nom_Complet,Pays_Residence,Date_Entree_Relation,Montant_Investi_CHF,Type_Client
0,1,Jean Dupont,Suisse,2021-03-15,250000,Particulier
1,2,Maria Silva,Portugal,2020-07-01,180000,Particulier
2,3,Alexei Petrov,Russie,2019-11-20,1200000,Particulier
3,4,Fatima Al Rashid,Emirats Arabes Unis,2022-01-10,950000,Particulier
4,5,Hans Müller,Allemagne,2018-05-05,320000,Particulier
5,6,Li Wei,Chine,2021-09-12,780000,Particulier
6,7,Carlos Fernandez,Panama,2020-02-28,500000,Societe
7,8,Anna Kowalski,Pologne,2022-06-18,90000,Particulier
8,9,Kim Jong Park,Coree du Sud,2019-04-03,410000,Particulier
9,10,Isabella Rossi,Italie,2021-12-01,275000,Particulier
10,11,Mohammed Al Fulan,Iran,2020-10-14,630000,Particulier
11,12,Sophie Martin,France,2023-02-20,150000,Particulier
12,13,Viktor Yanukovich,Ukraine,2018-08-09,2100000,Particulier
13,14,Grace Chen,Singapour,2022-03-30,340000,Societe
14,15,Ahmed Hassan,Egypte,2021-07-22,220000,Particulier
15,16,Elena Popescu,Roumanie,2020-05-17,175000,Particulier
16,17,David Cohen,Israel,2019-09-25,890000,Particulier
17,18,Ravi Patel,Inde,2022-11-05,260000,Particulier
18,19,Olga Ivanova,Bielorussie,2020-01-30,540000,Particulier
19,20,Thomas Weber,Suisse,2023-04-11,130000,Particulier

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ID_Client             20 non-null     int64
 1   Nom_Complet           20 non-null     object
 2   Pays_Residence        20 non-null     object
 3   Date_Entree_Relation  20 non-null     object
 4   Montant_Investi_CHF   20 non-null     int64
 5   Type_Client           20 non-null     object
dtypes: int64(2), object(4)
memory usage: 1.1+ KB

In [ ]:
df.sort_values("Montant_Investi_CHF", ascending=False)

,ID_Client,Nom_Complet,Pays_Residence,Date_Entree_Relation,Montant_Investi_CHF,Type_Client
12,13,Viktor Yanukovich,Ukraine,2018-08-09,2100000,Particulier
2,3,Alexei Petrov,Russie,2019-11-20,1200000,Particulier
3,4,Fatima Al Rashid,Emirats Arabes Unis,2022-01-10,950000,Particulier
16,17,David Cohen,Israel,2019-09-25,890000,Particulier
5,6,Li Wei,Chine,2021-09-12,780000,Particulier
10,11,Mohammed Al Fulan,Iran,2020-10-14,630000,Particulier
18,19,Olga Ivanova,Bielorussie,2020-01-30,540000,Particulier
6,7,Carlos Fernandez,Panama,2020-02-28,500000,Societe
8,9,Kim Jong Park,Coree du Sud,2019-04-03,410000,Particulier
13,14,Grace Chen,Singapour,2022-03-30,340000,Societe
4,5,Hans Müller,Allemagne,2018-05-05,320000,Particulier
9,10,Isabella Rossi,Italie,2021-12-01,275000,Particulier
17,18,Ravi Patel,Inde,2022-11-05,260000,Particulier
0,1,Jean Dupont,Suisse,2021-03-15,250000,Particulier
14,15,Ahmed Hassan,Egypte,2021-07-22,220000,Particulier
1,2,Maria Silva,Portugal,2020-07-01,180000,Particulier
15,16,Elena Popescu,Roumanie,2020-05-17,175000,Particulier
11,12,Sophie Martin,France,2023-02-20,150000,Particulier
19,20,Thomas Weber,Suisse,2023-04-11,130000,Particulier
7,8,Anna Kowalski,Pologne,2022-06-18,90000,Particulier

In [ ]:
pays_a_risque = ["Russie", "Iran", "Panama", "Bielorussie"]

In [ ]:
df[df["Pays_Residence"].isin(pays_a_risque)]

,ID_Client,Nom_Complet,Pays_Residence,Date_Entree_Relation,Montant_Investi_CHF,Type_Client
2,3,Alexei Petrov,Russie,2019-11-20,1200000,Particulier
6,7,Carlos Fernandez,Panama,2020-02-28,500000,Societe
10,11,Mohammed Al Fulan,Iran,2020-10-14,630000,Particulier
18,19,Olga Ivanova,Bielorussie,2020-01-30,540000,Particulier

In [ ]:
df[df["Montant_Investi_CHF"] > 500000]

,ID_Client,Nom_Complet,Pays_Residence,Date_Entree_Relation,Montant_Investi_CHF,Type_Client
2,3,Alexei Petrov,Russie,2019-11-20,1200000,Particulier
3,4,Fatima Al Rashid,Emirats Arabes Unis,2022-01-10,950000,Particulier
5,6,Li Wei,Chine,2021-09-12,780000,Particulier
10,11,Mohammed Al Fulan,Iran,2020-10-14,630000,Particulier
12,13,Viktor Yanukovich,Ukraine,2018-08-09,2100000,Particulier
16,17,David Cohen,Israel,2019-09-25,890000,Particulier
18,19,Olga Ivanova,Bielorussie,2020-01-30,540000,Particulier

In [ ]:
df[(df["Pays_Residence"].isin(pays_a_risque)) & (df["Montant_Investi_CHF"] > 500000)]

,ID_Client,Nom_Complet,Pays_Residence,Date_Entree_Relation,Montant_Investi_CHF,Type_Client
2,3,Alexei Petrov,Russie,2019-11-20,1200000,Particulier
10,11,Mohammed Al Fulan,Iran,2020-10-14,630000,Particulier
18,19,Olga Ivanova,Bielorussie,2020-01-30,540000,Particulier

In [ ]:
import pandas as pd
df = pd.read_excel("clients_fictifs_AML.xlsx")
df

,ID_Client,Nom_Complet,Pays_Residence,Date_Entree_Relation,Montant_Investi_CHF,Type_Client
0,1,Jean Dupont,Suisse,2021-03-15,250000,Particulier
1,2,Maria Silva,Portugal,2020-07-01,180000,Particulier
2,3,Alexei Petrov,Russie,2019-11-20,1200000,Particulier
3,4,Fatima Al Rashid,Emirats Arabes Unis,2022-01-10,950000,Particulier
4,5,Hans Müller,Allemagne,2018-05-05,320000,Particulier
5,6,Li Wei,Chine,2021-09-12,780000,Particulier
6,7,Carlos Fernandez,Panama,2020-02-28,500000,Societe
7,8,Anna Kowalski,Pologne,2022-06-18,90000,Particulier
8,9,Kim Jong Park,Coree du Sud,2019-04-03,410000,Particulier
9,10,Isabella Rossi,Italie,2021-12-01,275000,Particulier
10,11,Mohammed Al Fulan,Iran,2020-10-14,630000,Particulier
11,12,Sophie Martin,France,2023-02-20,150000,Particulier
12,13,Viktor Yanukovich,Ukraine,2018-08-09,2100000,Particulier
13,14,Grace Chen,Singapour,2022-03-30,340000,Societe
14,15,Ahmed Hassan,Egypte,2021-07-22,220000,Particulier
15,16,Elena Popescu,Roumanie,2020-05-17,175000,Particulier
16,17,David Cohen,Israel,2019-09-25,890000,Particulier
17,18,Ravi Patel,Inde,2022-11-05,260000,Particulier
18,19,Olga Ivanova,Bielorussie,2020-01-30,540000,Particulier
19,20,Thomas Weber,Suisse,2023-04-11,130000,Particulier

In [ ]:
df_sanctions = pd.read_excel("liste_sanctions_fictive.xlsx")
df_sanctions

,ID_Sanction,Nom_Liste,Organisme,Motif
0,1,Alexei Petrov,Liste fictive UE,Gel des avoirs - liens present
1,2,Viktor Yanukovich,Liste fictive UE,Gel des avoirs - ancien officiel
2,3,Mohamed Al Fulan,Liste fictive ONU,Financement illicite presume
3,4,Olha Ivanova,Liste fictive OFAC,Contournement de sanctions
4,5,Nikolai Sokolov,Liste fictive UE,Gel des avoirs
5,6,Boris Volkov,Liste fictive ONU,Activites illicites presumees
6,7,Yusuf Al Karim,Liste fictive OFAC,Financement illicite
7,8,Igor Petrovic,Liste fictive UE,Gel des avoirs

In [ ]:
matches_exacts = df[df["Nom_Complet"].isin(df_sanctions["Nom_Liste"])]
matches_exacts

,ID_Client,Nom_Complet,Pays_Residence,Date_Entree_Relation,Montant_Investi_CHF,Type_Client
2,3,Alexei Petrov,Russie,2019-11-20,1200000,Particulier
12,13,Viktor Yanukovich,Ukraine,2018-08-09,2100000,Particulier

In [ ]:
!pip install rapidfuzz

Collecting rapidfuzz
  Downloading rapidfuzz-3.14.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (12 kB)
Downloading rapidfuzz-3.14.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 33.1 MB/s eta 0:00:00
Installing collected packages: rapidfuzz
Successfully installed rapidfuzz-3.14.5

In [ ]:
from rapidfuzz import fuzz

resultats = []

for nom_client in df["Nom_Complet"]:
    for nom_sanction in df_sanctions["Nom_Liste"]:
        score = fuzz.ratio(nom_client, nom_sanction)
        if score > 80:  # seuil de similarité à ajuster
            resultats.append({
                "Client": nom_client,
                "Nom_Sanction_Proche": nom_sanction,
                "Score_Similarite": score
            })

alertes = pd.DataFrame(resultats)
alertes.sort_values("Score_Similarite", ascending=False)

              Client Nom_Sanction_Proche  Score_Similarite
0      Alexei Petrov       Alexei Petrov        100.000000
2  Viktor Yanukovich   Viktor Yanukovich        100.000000
1  Mohammed Al Fulan    Mohamed Al Fulan         96.969697
3       Olga Ivanova        Olha Ivanova         91.666667

In [ ]:
from rapidfuzz import fuzz

resultats = []

for nom_client in df["Nom_Complet"]:
    for nom_sanction in df_sanctions["Nom_Liste"]:
        score = fuzz.ratio(nom_client, nom_sanction)
        if score > 80:  # seuil de similarité à ajuster
            resultats.append({
                "Client": nom_client,
                "Nom_Sanction_Proche": nom_sanction,
                "Score_Similarite": score
            })

alertes = pd.DataFrame(resultats)
alertes.sort_values("Score_Similarite", ascending=False)

              Client Nom_Sanction_Proche  Score_Similarite
0      Alexei Petrov       Alexei Petrov        100.000000
2  Viktor Yanukovich   Viktor Yanukovich        100.000000
1  Mohammed Al Fulan    Mohamed Al Fulan         96.969697
3       Olga Ivanova        Olha Ivanova         91.666667

In [ ]:
df_tx = pd.read_excel("transactions_fictives_AML.xlsx")
df_tx

,ID_Transaction,ID_Client,Date,Montant_CHF,Type,Pays_Destination
0,1,1,2024-01-13,11252.48,Virement,France
1,2,1,2024-04-24,2523.30,Virement,Suisse
2,3,2,2024-10-29,6617.87,Virement,Suisse
3,4,2,2024-02-17,3670.25,Virement,Portugal
4,5,3,2024-10-14,3383.15,Virement,Portugal
...,...,...,...,...,...,...
72,73,19,2024-09-02,3242.45,Virement,Chypre
73,74,19,2024-09-03,6202.37,Virement,Panama
74,75,19,2024-09-03,3994.63,Virement,Iles Caiman
75,76,19,2024-09-04,5145.14,Virement,Iles Caiman
76,77,19,2024-09-04,4687.53,Virement,Chypre

In [ ]:
seuil_bas, seuil_haut = 9000, 9999

In [ ]:
df_tx[(df_tx["Montant_CHF"] >= seuil_bas) & (df_tx["Montant_CHF"] <= seuil_haut)]

,ID_Transaction,ID_Client,Date,Montant_CHF,Type,Pays_Destination
10,11,5,2024-06-25,9254.03,Virement,Suisse
13,14,5,2024-11-17,9468.54,Virement,Allemagne
17,18,7,2024-08-20,9717.42,Virement,Allemagne
20,21,7,2024-11-07,9707.19,Virement,Portugal
33,34,11,2024-03-19,9597.97,Virement,Italie
38,39,12,2025-01-28,9793.95,Virement,Suisse
45,46,14,2024-01-01,9184.70,Virement,Italie
56,57,19,2024-01-11,9030.48,Virement,France
58,59,19,2024-12-28,9650.99,Virement,France
62,63,3,2024-06-01,9603.35,Virement,Panama
63,64,3,2024-06-02,9370.10,Virement,Panama
64,65,3,2024-06-03,9531.08,Virement,Panama
65,66,3,2024-06-04,9484.94,Virement,Panama
66,67,3,2024-06-05,9266.03,Virement,Panama
67,68,3,2024-06-06,9661.29,Virement,Panama

In [ ]:
seuil_gros = 100000

In [ ]:
df_tx[df_tx["Montant_CHF"] > seuil_gros]

,ID_Transaction,ID_Client,Date,Montant_CHF,Type,Pays_Destination
68,69,11,2024-08-15,480000.0,Virement,Iles Caiman

In [ ]:
df_tx.groupby("ID_Client").size().sort_values(ascending=False)

ID_Client
19    12
3      8
11     6
10     5
13     4
7      4
4      4
5      4
18     3
9      3
8      3
6      3
17     3
14     3
1      2
2      2
12     2
15     2
16     2
20     2
dtype: int64

In [ ]:
!pip install openpyxl

Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)

In [ ]:
from datetime import datetime

with pd.ExcelWriter("rapport_AML.xlsx", engine="openpyxl") as writer:

    # Feuille 1 : correspondances exactes sur la liste de sanctions
    matches_exacts.to_excel(writer, sheet_name="Sanctions_Exactes", index=False)

    # Feuille 2 : correspondances approximatives (fuzzy matching)
    alertes.to_excel(writer, sheet_name="Sanctions_Fuzzy", index=False)

    # Feuille 3 : transactions suspectes (structuring)
    structuring = df_tx[(df_tx["Montant_CHF"] >= 9000) & (df_tx["Montant_CHF"] <= 9999)]
    structuring.to_excel(writer, sheet_name="Structuring", index=False)

    # Feuille 4 : transactions à montant inhabituel
    gros_montants = df_tx[df_tx["Montant_CHF"] > 100000]
    gros_montants.to_excel(writer, sheet_name="Montants_Eleves", index=False)

    # Feuille 5 : résumé synthétique
    resume = pd.DataFrame({
        "Indicateur": [
            "Date du rapport",
            "Nb clients screenés",
            "Nb correspondances exactes",
            "Nb correspondances fuzzy",
            "Nb transactions structuring",
            "Nb transactions montant élevé"
        ],
        "Valeur": [
            datetime.now().strftime("%Y-%m-%d"),
            len(df),
            len(matches_exacts),
            len(alertes),
            len(structuring),
            len(gros_montants)
        ]
    })
    resume.to_excel(writer, sheet_name="Resume", index=False)

print("Rapport généré avec succès")

Rapport généré avec succès